# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"a\n\x0f\x41nalysisRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04zone\x18\x02 \x01(\t\x12\x10\n\x08sensorId\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61teFrom\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x61teTo\x18\x05 \x01(\t\"g\n\x0e\x41nalysisResult\x12\x15\n\rresultSummary\x18\x01 \x01(\t\x12\x17\n\x0f\x63omputedAverage\x18\x02 \x01(\x01\x12\x12\n\nalertLevel\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"I\n\x11PredictionRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04zone\x18\x02 \x01(\t\x12\x18\n\x10periodsToPredict\x18\x03 \x01(\x05\"@\n\x10PredictionResult\x12\x19\n\x11predictionSummary\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\x95\x01\n\x0f\x41nalysisService\x12>\n\x07\x41nalyze\x12\x19.analysis.AnalysisRequest\x1a\x18.analysis.AnalysisResult\x12\x42\n\x07Predict\x12\x1b.analysis.PredictionRequest\x1a\x1a.analysis.PredictionResultB\x0b\xaa\x02\x08\x41nalysisb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\010Analysis'
  _globals['_ANALYSISREQUEST']._serialized_start=28
  _globals['_ANALYSISREQUEST']._serialized_end=125
  _globals['_ANALYSISRESULT']._serialized_start=127
  _globals['_ANALYSISRESULT']._serialized_end=230
  _globals['_PREDICTIONREQUEST']._serialized_start=232
  _globals['_PREDICTIONREQUEST']._serialized_end=305
  _globals['_PREDICTIONRESULT']._serialized_start=307
  _globals['_PREDICTIONRESULT']._serialized_end=371
  _globals['_ANALYSISSERVICE']._serialized_start=374
  _globals['_ANALYSISSERVICE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
