# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preprocessing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'preprocessing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13preprocessing.proto\x12\rpreprocessing\"}\n\nRawReading\x12\x10\n\x08sensorId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x11\n\trawFormat\x18\x06 \x01(\t\x12\x0c\n\x04zone\x18\x07 \x01(\t\"\x95\x01\n\x11NormalizedReading\x12\x10\n\x08sensorId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x11\n\trawFormat\x18\x06 \x01(\t\x12\x0f\n\x07isValid\x18\x07 \x01(\x08\x12\x0c\n\x04zone\x18\x08 \x01(\t2`\n\x14PreprocessingService\x12H\n\tNormalize\x12\x19.preprocessing.RawReading\x1a .preprocessing.NormalizedReadingB\x10\xaa\x02\rPreprocessingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preprocessing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\rPreprocessing'
  _globals['_RAWREADING']._serialized_start=38
  _globals['_RAWREADING']._serialized_end=163
  _globals['_NORMALIZEDREADING']._serialized_start=166
  _globals['_NORMALIZEDREADING']._serialized_end=315
  _globals['_PREPROCESSINGSERVICE']._serialized_start=317
  _globals['_PREPROCESSINGSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
