<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Servidor</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Copiar o ficheiro appsettings.json para o diretório de saída -->
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Grpc.Tools" Version="2.62.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Grpc.Net.Client" Version="2.62.0" />
    <PackageReference Include="Google.Protobuf" Version="3.26.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.8.1" />
    <PackageReference Include="Polly" Version="8.6.6" />
    <PackageReference Include="Spectre.Console" Version="0.55.2" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\proto\analysis.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\SensorTypes.cs" Link="Shared\SensorTypes.cs" />
    <Compile Include="..\Shared\ProtocolConstants.cs" Link="Shared\ProtocolConstants.cs" />
  </ItemGroup>

</Project>
